from pydantic import BaseModel, Field

class CoverTypePayload(BaseModel):
    # 10 Continuous/Numerical Features
    Elevation: int = Field(2500, description="Elevation in meters (1859 - 3858)")
    Aspect: int = Field(135, description="Aspect in degrees azimuth (0 - 360)")
    Slope: int = Field(15, description="Slope in degrees (0 - 66)")
    Horizontal_Distance_To_Hydrology: int = Field(200, description="Horizontal distance to nearest surface water features (0 - 1343)")
    Vertical_Distance_To_Hydrology: int = Field(30, description="Vertical distance to nearest surface water features (-147 - 601)")
    Horizontal_Distance_To_Roadways: int = Field(2000, description="Horizontal distance to nearest roadway (0 - 7117)")
    Hillshade_9am: int = Field(200, description="Hillshade index at 9 am (0 - 254)")
    Hillshade_Noon: int = Field(220, description="Hillshade index at noon (0 - 254)")
    Hillshade_3pm: int = Field(130, description="Hillshade index at 3 pm (0 - 254)")
    Horizontal_Distance_To_Fire_Points: int = Field(1500, description="Horizontal distance to nearest fire ignition point (0 - 7173)")

    # 4 Wilderness Areas (Binary/One-Hot Encoded)
    Wilderness_Area_01: int = Field(1, description="Binary: Rawah Wilderness Area")
    Wilderness_Area_02: int = Field(0, description="Binary: Neota Wilderness Area")
    Wilderness_Area_03: int = Field(0, description="Binary: Comanche Peak Wilderness Area")
    Wilderness_Area_04: int = Field(0, description="Binary: Cache la Poudre Wilderness Area")

    # 40 Soil Types (Binary/One-Hot Encoded) - Typically only one is 1, the rest 0
    Soil_Type_01: int = Field(0)
    Soil_Type_02: int = Field(0)
    Soil_Type_03: int = Field(0)
    Soil_Type_04: int = Field(0)
    Soil_Type_05: int = Field(0)
    Soil_Type_06: int = Field(0)
    Soil_Type_07: int = Field(0)
    Soil_Type_08: int = Field(0)
    Soil_Type_09: int = Field(0)
    Soil_Type_10: int = Field(0)
    Soil_Type_11: int = Field(0)
    Soil_Type_12: int = Field(0)
    Soil_Type_13: int = Field(0)
    Soil_Type_14: int = Field(0)
    Soil_Type_15: int = Field(0)
    Soil_Type_16: int = Field(0)
    Soil_Type_17: int = Field(0)
    Soil_Type_18: int = Field(0)
    Soil_Type_19: int = Field(0)
    Soil_Type_20: int = Field(0)
    Soil_Type_21: int = Field(0)
    Soil_Type_22: int = Field(0)
    Soil_Type_23: int = Field(1) # Setting one of them to 1 for example payload
    Soil_Type_24: int = Field(0)
    Soil_Type_25: int = Field(0)
    Soil_Type_26: int = Field(0)
    Soil_Type_27: int = Field(0)
    Soil_Type_28: int = Field(0)
    Soil_Type_29: int = Field(0)
    Soil_Type_30: int = Field(0)
    Soil_Type_31: int = Field(0)
    Soil_Type_32: int = Field(0)
    Soil_Type_33: int = Field(0)
    Soil_Type_34: int = Field(0)
    Soil_Type_35: int = Field(0)
    Soil_Type_36: int = Field(0)
    Soil_Type_37: int = Field(0)
    Soil_Type_38: int = Field(0)
    Soil_Type_39: int = Field(0)
    Soil_Type_40: int = Field(0)

class CoverTypeResponse(BaseModel):
    """Output structure for the Cover Type prediction."""
    cover_type: int = Field(3, description="Predicted Cover Type class (1-7)")
